import Route from '@ember/routing/route';

export default Route.extend({
	model() {
		return [
			"Troca de Correia Dentada",
			"Revisão das Correias do Motor",
			"Troca de Rolamento da Correia",
			"Troca de Polia da Correia",
			"Revisão do Tensor da Correia Dentada",
			"Troca de Filtro de Óleo",
			"Troca de Filtro de Ar",
			"Troca de Filtro de Cabine",
			"Troca de Filtro de Combustível",
			"Troca de Fluido de Freio",
			"Troca de Líquido de Arrefecimento",
			"Troca de Fluido de Transmissao", 
			"Revisão do Fluido de Freio",
			"Troca do Fluido de Direção",
			"Revisão do Fluido de Direção Hidráulica",
			"Revisão do Líquido de Arrefecimento",
			"Revisão do Óleo de Câmbio",
			"Revisão completa do Motor",
			"Revisão veicular completa",
			"Revisão do Sistema de Arrefecimento",
			"Troca dos Pneus",
			"Alinhamento do Carro",
			"Balanceamento de Pneus",
			"Alinhamento e Balanceamento", 
			"Revisão da Direção Hidráulica",
			"Revisão dos Pneus",
			"Rodízio de Pneus", 
			"Troca das Pastilhas de Freio",
			"Revisão do Sistema de Freio",
			"Troca dos Discos de Freio",
			"Troca do Jogo de Pastilhas de Freio",
			"Revisão do Freio ABS",
			"Troca da Chave de Ignição",
			"Revisão do Sistema de Ignição",
			"Troca das Velas de Ignição",
			"Limpeza das Velas de Ignição",
			"Troca dos Cabos de Vela",
			"Troca da Bateria",
			"Troca do Alternador",
			"Revisão do motor de arranque",
			"Revisão do Alternador",
			"Revisão da Bateria",
			"Revisão do Sistema de Injeção Eletrônica e Abastecimento",
			"Troca de Óleo do Motor",
			"Troca dos Amortecedores Dianteiros",
			"Troca dos Amortecedores Traseiros",
			"Reviso do Sistema de Suspensão",
			"Revisão do Sistema de Transmissão"
		]
	}
});
